version: '3'
services:
  auth:
    image: cyberadvance/auth-service
    ports:
      - "3001:3000"
    environment:
      - MONGO_DB_URI=mongodb://54.255.180.155:3099/dropAcc
      - AMQP_URL=amqp://18.136.211.198
    deploy:
      replicas: 1
  sale:
    image: cyberadvance/acc-sale-service
    ports:
      - "3002:3000"
    environment:
      - MONGO_DB_URI=mongodb://54.255.180.155:3099/dropAcc
      - AMQP_URL=amqp://18.136.211.198
    deploy:
      replicas: 1